### PR TITLE
Bump version to 1.8.1.2

### PR DESCRIPTION
**Pull request by maxhora**

### CODE REVIEW

**Comment by rmax** [comment]
Error seems related to https://github.com/lz4/lz4/issues/450

**Comment by rmax** [comment]
I see two options:

* Wait for the next release.
* Apply the patch https://github.com/lz4/lz4/commit/ad12efa4e80855eb6267f5d3a7c50669e0565919#diff-d6890d30fd81aaa0c63351bb92783cf7R196 (and expect there are no more compiling errors).

**Comment by maxhora** [comment]
Hey @rmax , thank you for looking into that!
Maybe, next release or I will try to apply patch, if release time will take too long, thanks!

**Comment by rmax** [comment]
@MaxRis good choice! Trying to backport patches can lead to a rabbit hole. Let's wait for the next release.

**Comment by jakirkham** [comment]
Think we fixed the compiler issue in PR ( https://github.com/conda-forge/lz4-c-feedstock/pull/9 ). So took the liberty of merging your PR with `master`. It appears to pass now.

**Comment by jakirkham** [comment]
Is it alright to merge this, @rmax? Appears this version is in `defaults` now.

**Comment by rmax** [comment]
Thanks @jakirkham

**Comment by rmax** [comment]
By the way, @jakirkham do you suggest to stop release this version and leave it to the `defaults` channel?

**Comment by jakirkham** [comment]
No, there's value in having it here even if it lags or passes `defaults`. [This comment]( https://github.com/conda-forge/staged-recipes/issues/5967#issuecomment-392866985 ) encapsulates this well.

Would add that `defaults` and `conda-forge` do collaborate, but to a limited extent at present. This will improve once we have migrated to `conda-build` 3 completely, use the new compilers, and settle on a common pinning scheme. Work is being done on all of these fronts, but it takes a while as it involves a lot of changes throughout the stack.

**Comment by jakirkham** [comment]
Thanks @rmax and @MaxRis :)

**Pull request merged**
